language: python
python:
    - "3.6"

services:
    - docker

env:
  - DOCKER_SUFFIX=py36-nompi
  - DOCKER_SUFFIX=py36-mpi

install:
  - pip install flake8
  - docker build -f test.dockerfile.${DOCKER_SUFFIX} -t baselines-test .

script:
  - flake8 . --show-source --statistics
  - docker run baselines-test pytest -v .
