language: python
python:
    - "3.6"

services:
    - docker

env:
  - DOCKER_SUFFIX=py36-nompi
  - DOCKER_SUFFIX=py36-mpi

install: "" # so travis doesn't do pip install requirements.txt
script:
  - flake8 . --show-source --statistics
  - docker build -f test.dockerfile.${DOCKER_SUFFIX} -t baselines-test .
